/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "webrtcConf.h"

/* Header for class com_example_meeting_Meeting */

#ifndef _Included_com_example_meeting_Meeting
#define _Included_com_example_meeting_Meeting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_meeting_Meeting
 * Method:    createConference
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_meeting_Meeting_createConference
  (JNIEnv *, jclass);

/*
 * Class:     com_example_meeting_Meeting
 * Method:    joinConference
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_meeting_Meeting_joinConference
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_meeting_Meeting
 * Method:    dropConference
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_meeting_Meeting_dropConference
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_meeting_Meeting
 * Method:    networkDelay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_meeting_Meeting_networkDelay
  (JNIEnv *, jclass,jint);

/*
 * Class:     com_example_meeting_Meeting
 * Method:    newtworkLoss
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_meeting_Meeting_newtworkLoss
  (JNIEnv *, jclass,jint);

/*
 * Class:     com_example_meeting_Meeting
 * Method:    conferenceOver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_meeting_Meeting_conferenceOver
  (JNIEnv *, jclass);

/*
 * Class:     com_example_meeting_Meeting
 * Method:    getData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_meeting_Meeting_getData
  (JNIEnv *, jclass);

typedef struct __IdData
{
    MPartiHandle p;
    int num;
} IdData,*PIdData;


void* readData(void *arg);
void initAudio(PMParticipant p,int id);
void thread_exit_handler(int sig);
void* writeAudio(void*);

#ifdef __cplusplus
}
#endif
#endif
